version: "3.9"

services:
  backend:
    container_name: corpsys-backend
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./back:/back
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - .env
    depends_on:
      - database

  database:
    container_name: corpsys-psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - .env

  # frontend:
  #   container_name: corpsys-frontend
  #   build:
  #     context: .
  #   ports:
  #     - 5173:3000
  #   volumes:
  #     - ./front:/app
  #   depends_on:
  #     - backend
